name: SmidgeThing
version: ${project.version}
main: SmidgeThing
api-version: 1.19
authors: [hicupalot]

commands:
  ToggleAdminChat:
    description: Toggle/Speak the Admin Chat
    usage: /ac
    permission: smidge.adminChat
    aliases: [adminchat, ac]
  ToggleStaffChat:
    description: Toggle/Speak the Staff Chat
    usage: /sc
    permission: smidge.staffChat
    aliases: [staffchat, sc]
  ToggleStreamerChat:
    description: Toggle/Speak in Streamer Chat
    usage: /streamchat
    permission: smidge.streamerChat
    aliases: [streamchat, streamerchat]
  permissions:
    smidge.staffChat:
      descritpion: 'Allows you to speak in Staff Chat'
      default: op
    smidge.adminChat:
      descritpion: 'Allows you to speak in Admin Chat'
      default: op
    smidge.streamerChat:
     description: 'Allows you to speak in Streamer Chat'
     default: op
