name: SmidgeThing
version: ${project.version}
main: SmidgeThing
api-version: 1.19
authors: [hicupalot]
depend: [SuperVanish]
commands:
  ToggleAdminChat:
    description: Toggle/Speak the Admin Chat
    usage: /ac
    permission: smidge.adminChat
    aliases: [adminchat, ac]
  ToggleStaffChat:
    description: Toggle/Speak the Staff Chat
    usage: /sc
    permission: smidge.staffChat
    aliases: [staffchat, sc]
  ToggleStreamerChat:
    description: Toggle/Speak in Streamer Chat
    usage: /streamchat
    permission: smidge.streamerChat
    aliases: [streamchat, streamerchat]
  Follower:
    description: Monitor a Player
    usage: /spy
    permission: smidge.spy
    aliases: [investigate, monitor, spy]
  TogglepetKiller:
    description: Toggle Pet Killing
    usage: /petkilltoggle
    permission: smidge.petKiller
    aliases: [petkill, killpet]
  clearchat:
    description: Clears the chat
    usage: /clearchat
    permission: smidge.clearchat
    aliases: [chatclear, cc]
  permissions:
    smidge.staffChat:
      descritpion: 'Allows you to speak in Staff Chat'
      default: op
    smidge.adminChat:
      descritpion: 'Allows you to speak in Admin Chat'
      default: op
    smidge.streamerChat:
     description: 'Allows you to speak in Streamer Chat'
     default: op
    smidge.spy:
      description: 'Allows you to monitor other users'
      default: op
    smidge.petKiller:
      description: 'Allows you to toggle killing pets'
      default: op
    smidge.clearchat:
      description: 'Allows you to clear chat'
      default: op


