name: SmidgeThing
version: ${project.version}
main: SmidgeThing
api-version: 1.19
authors: [hicupalot]
depend: [SuperVanish]
commands:
  ToggleAdminChat:
    description: Toggle/Speak the Admin Chat
    usage: /ac
    permission: smidge.admin
    aliases: [adminchat, ac]
  ToggleStaffChat:
    description: Toggle/Speak the Staff Chat
    usage: /sc
    permission: smidge.staff
    aliases: [staffchat, sc]
  ToggleStreamerChat:
    description: Toggle/Speak in Streamer Chat
    usage: /streamchat
    permission: smidge.streamer
    aliases: [streamchat, streamerchat]
 # Follower:
 #   description: Monitor a Player
 #   usage: /follower
 #   permission: smidge.spy
 #   aliases: [investigate, monitor, spy]
  TogglepetKiller:
    description: Toggle Pet Killing
    usage: /petkilltoggle
    permission: smidge.staff
    aliases: [petkill, killpet]
  clearchat:
    description: Clears the chat
    usage: /clearchat
    permission: smidge.staff
    aliases: [chatclear, cc]
  mutechat:
    description: Mutes the Chat
    usage: /mutechat
    permission: smidge.staff
    aliases: [chatmute, mc, silence]
  kickall:
    description: Kicks all players
    usage: /kickall
    permission: smidge.staff
  maintenancetoggle:
    description: Toggles Maintenance Mode
    usage: /maintenance
    permission: smidge.admin
  DebugWeapon:
    description: Gives you a debug weapon
    usage: /debugweapon
    permission: smidge.admin
  permissions:
    smidge.staff:
      descritpion: 'Allows Access To Staff Commands'
      default: op
    smidge.admin:
      descritpion: 'Allows access to Admin Commands'
      default: op
    smidge.streamer:
     description: 'Allows access to Streamer Commands'
     default: op
    smidge.spy:
      description: 'Allows you to monitor other users'
      default: op
    smidge.maintenance:
      description: 'Join During Maintenance'
      default: op


